// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cixmumcijrekcqzazmhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpeG11bWNpanJla2NxemF6bWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzQ4MDcsImV4cCI6MjA2NTU1MDgwN30.HlAKxFBH-iMael3JyLxHse1PfKegzubFk4bY6wA3yCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);